%Doctor.Config{
  ignore_modules: [
    # Spark/Ash/Jido generate helper modules that either point at `nofile` or
    # expand quoted DSL code in ways Doctor cannot attribute cleanly.
    ~r/^Inspect\.Jidoka\.Demo\./,
    ~r/^Jidoka\.Agent\.Dsl/,
    ~r/^Jidoka\.Agent\.Verifiers\./,
    Jidoka.Context,
    Jidoka.Debug,
    Jidoka.Error.Normalize,
    ~r/^Jidoka\.Error\.Normalize\./,
    Jidoka.Workflow.Build,
    Jidoka.Workflow.Codegen,
    Jidoka.Workflow.Definition,
    ~r/^Jidoka\.Workflow\.Dsl/,
    ~r/^Jidoka\.Workflow\.Runtime\./,
    ~r/^Jidoka\.Demo\./,
    ~r/^Jidoka\.AgentView\.(Defaults|Projection|Start|TurnState)$/,
    Jidoka.Chat,
    Jidoka.Guardrails,
    ~r/^Jidoka\.Guardrails\./,
    Jidoka.Hooks,
    ~r/^Jidoka\.Hooks\./,
    Jidoka.ImportedAgent,
    ~r/^Jidoka\.ImportedAgent\./,
    Jidoka.Inspection,
    ~r/^Jidoka\.Kino\.(AgentView|Chat|ContextView|LogTrace|Render|RuntimeSetup|TraceView)$/,
    Jidoka.Memory,
    Jidoka.Memory.Config,
    Jidoka.MCP.Sync,
    ~r/^Jidoka\.Output\.(Config|Error|Runtime|Schema)$/,
    ~r/^Jidoka\.Plugins\./,
    Jidoka.Schedule.Executor,
    Jidoka.Skill,
    Jidoka.StageRefs,
    ~r/^Jidoka\.Subagent\.(Context|Definition|Metadata|Runtime|Tool)/,
    ~r/^Jidoka\.Web\.(Config|Runtime)$/
  ],
  ignore_paths: [
    "nofile",
    ~r"^lib/mix/tasks/",
    ~r"^lib/jidoka/error/normalize\.ex$",
    ~r"^lib/jidoka/agent/",
    ~r"^lib/jidoka/demo/",
    ~r"^lib/jidoka/workflow/(build|codegen|definition|spark_dsl)\.ex$",
    ~r"^lib/jidoka/workflow/dsl/",
    ~r"^lib/jidoka/plugins/",
    ~r"^lib/jidoka/imported_agent/(codec|registries)\.ex$",
    ~r"^lib/jidoka/mcp/",
    ~r"^lib/jidoka/subagent/"
  ],
  min_module_doc_coverage: 60,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 90,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 0,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: false,
  umbrella: false
}
