[
  import_deps: [:jidoka, :ash],
  locals_without_parens: [
    agent: 1,
    agent: 2,
    agent: 3,
    ash_resource: 1,
    capabilities: 1,
    context: 1,
    defaults: 1,
    description: 1,
    function: 2,
    function: 3,
    from: 1,
    from: 2,
    handoff: 1,
    handoff: 2,
    id: 1,
    input: 1,
    input_guardrail: 1,
    instructions: 1,
    live: 3,
    model: 1,
    output: 1,
    pipe_through: 1,
    plug: 1,
    plug: 2,
    schema: 1,
    scope: 2,
    socket: 3,
    steps: 1,
    subagent: 1,
    subagent: 2,
    tool: 2,
    tool: 3,
    value: 1,
    workflow: 1,
    workflow: 2
  ],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
]
